default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: sbts_development
  username: sbts_app
  password: 'Pa$$w0rd'

production:
  <<: *default
  database: sbts_production
  username: sbts_app
  password: 'Pa$$w0rd'

test:
  <<: *default
  database: sbts_test
  username: sbts_app
  password: 'Pa$$w0rd'